const ac = require('./utils/atcoder')
const cf = require('./utils/codeforces')
const cc = require('./utils/codechef')
const lc = require('./utils/leetcode')
const timeLink = require('./utils/timeanddatelink')
const DiscordJS = require('discord.js')
require('dotenv').config()
